image: $CI_REGISTRY/bigdata/algorithms/match_sivic/continuumio/miniconda3:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DEV_DELIVERY_PATH: "/export/home/edsdev/app/bigdata/"
  QUA_DELIVERY_PATH: "/export/home/edsqua/app/bigdata/"
  PRD_DELIVERY_PATH: "/export/home/edsprod/app/bigdata/"
  DEV_AIRFLOW_DELIVERY_PATH: "/export/home/edsdev/airflow/dags/bigdata/"
  QUA_AIRFLOW_DELIVERY_PATH: "/export/home/edsqua/airflow/dags/bigdata/"
  PRD_AIRFLOW_DELIVERY_PATH: "/export/home/edsprod/airflow/dags/bigdata/"

stages:
  - deploy-to-prod

deploy-to-production:
  stage: deploy-to-prod
  environment:
    name: prod
  script:
    - echo "Deploying the package to EDS cluster in the PRD environment"
    - rm -rf $PRD_DELIVERY_PATH/$CI_PROJECT_NAME || true
    - rm -rf $PRD_AIRFLOW_DELIVERY_PATH/$CI_PROJECT_NAME || true
    - mkdir -p $PRD_DELIVERY_PATH/$CI_PROJECT_NAME
    - mkdir -p $PRD_AIRFLOW_DELIVERY_PATH/$CI_PROJECT_NAME
    - cp dag/med_pipeline_prod.py $PRD_AIRFLOW_DELIVERY_PATH/$CI_PROJECT_NAME/
    - cp -r bin $PRD_DELIVERY_PATH/$CI_PROJECT_NAME/
    - cp -r pymedext_eds $PRD_DELIVERY_PATH/$CI_PROJECT_NAME/
    - cp deploy.py $PRD_DELIVERY_PATH/$CI_PROJECT_NAME/
    - cp run_pipeline_med.py $PRD_DELIVERY_PATH/$CI_PROJECT_NAME/
    - cp conf/conf_pipeline_med.cf $PRD_DELIVERY_PATH/$CI_PROJECT_NAME/
    - cp requirements.txt $PRD_DELIVERY_PATH/$CI_PROJECT_NAME/
    - mkdir -p $PRD_DELIVERY_PATH/$CI_PROJECT_NAME/data
    - cp $PRD_DELIVERY_PATHmodels/medicaments/* $PRD_DELIVERY_PATH/$CI_PROJECT_NAME/data/
    - chmod u+x $PRD_DELIVERY_PATH/$CI_PROJECT_NAME/bin/*.sh
    - chown -R 20015:20015 $PRD_DELIVERY_PATH/$CI_PROJECT_NAME
    - chown -R 20015:20015 $PRD_AIRFLOW_DELIVERY_PATH/$CI_PROJECT_NAME
  when: manual
