image: $CI_REGISTRY/bigdata/algorithms/match_sivic/continuumio/miniconda3:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DEV_DELIVERY_PATH: "/export/home/edsdev/app/bigdata/"
  QUA_DELIVERY_PATH: "/export/home/edsqua/app/bigdata/"
  PRD_DELIVERY_PATH: "/export/home/edsprod/app/bigdata/"
  DEV_AIRFLOW_DELIVERY_PATH: "/export/home/edsdev/airflow/dags/bigdata/"
  QUA_AIRFLOW_DELIVERY_PATH: "/export/home/edsqua/airflow/dags/bigdata/"
  PRD_AIRFLOW_DELIVERY_PATH: "/export/home/edsprod/airflow/dags/bigdata/"

stages:
  - deploy-to-prod

deploy-to-production:
  stage: deploy-to-prod
  environment:
    name: prod
  script:
    - echo "Deploying the package to EDS cluster in the PROD environment"
    - cd ../
    - rm -rf $PROD_DELIVERY_PATH/$CI_PROJECT_NAME || true
    - rm -rf $PROD_AIRFLOW_DELIVERY_PATH/$CI_PROJECT_NAME || true
    - mkdir -p $PROD_DELIVERY_PATH/$CI_PROJECT_NAME
    - mkdir -p $PROD_AIRFLOW_DELIVERY_PATH/$CI_PROJECT_NAME
    - cp dag/*_prod.py $PROD_AIRFLOW_DELIVERY_PATH/$CI_PROJECT_NAME/
    - cp -r bin $PROD_DELIVERY_PATH/$CI_PROJECT_NAME/
    - cp -r pymedext_eds $PROD_DELIVERY_PATH/$CI_PROJECT_NAME/
    - cp deploy.py $PROD_DELIVERY_PATH/$CI_PROJECT_NAME/
    - cp run_pipeline_med.py $PROD_DELIVERY_PATH/$CI_PROJECT_NAME/
    - cp conf/conf_pipeline_med.cf $PROD_DELIVERY_PATH/$CI_PROJECT_NAME/
    - cp requirements.txt $PROD_DELIVERY_PATH/$CI_PROJECT_NAME/
    - chown -R 20015:20015 $PROD_DELIVERY_PATH/$CI_PROJECT_NAME
    - chown -R 20015:20015 $PROD_AIRFLOW_DELIVERY_PATH/$CI_PROJECT_NAME
  when: manual
